import 'dart:io';
import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:url_launcher/url_launcher.dart';

class PatientInfusionRecord {
  final String patientName;
  final String fileNumber;
  final String salineType;
  final String duration;
  final DateTime startTime;
  final DateTime endTime;
  final String nurseName;
  PatientInfusionRecord({
    required this.patientName,
    required this.fileNumber,
    required this.salineType,
    required this.duration,
    required this.startTime,
    required this.endTime,
    required this.nurseName,
  });
}

class PdfService {
  
  Future<Uint8List> generateInfusionPdf(PatientInfusionRecord record) async {
    final pdf = pw.Document();
    // ملاحظة: لإضافة خط عربي، ضع ملف ttf في assets واستخدمه
    // final fontData = await rootBundle.load("assets/fonts/Cairo-Regular.ttf");
    // final arabicFont = pw.Font.ttf(fontData);

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text('Nurse Assistant - Infusion Report',
                        style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
                    pw.Text('${record.startTime.day}/${record.startTime.month}/${record.startTime.year}',
                        style: const pw.TextStyle(fontSize: 12)),
                  ],
                ),
              ),
              pw.SizedBox(height: 20),
              pw.Container(
                padding: const pw.EdgeInsets.all(12),
                decoration: pw.BoxDecoration(border: pw.Border.all(), borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8))),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    _pdfRow('Patient Name / اسم المريض:', record.patientName),
                    _pdfRow('File No / رقم الملف:', record.fileNumber),
                    _pdfRow('IV Fluid / نوع المحلول:', record.salineType),
                    _pdfRow('Duration / المدة:', record.duration),
                    _pdfRow('Start / البداية:', record.startTime.toString()),
                    _pdfRow('End / النهاية:', record.endTime.toString()),
                    _pdfRow('Nurse / الممرض:', record.nurseName),
                  ],
                ),
              ),
              pw.SizedBox(height: 20),
              pw.Text('Notes: IV line checked, no infiltration, patient tolerated well.',
                  style: const pw.TextStyle(fontSize: 11)),
              pw.Spacer(),
              pw.Divider(),
              pw.Text('Generated by Nurse Assistant App - For nursing use only',
                  style: pw.TextStyle(fontSize: 9, color: PdfColors.grey600)),
            ],
          );
        },
      ),
    );
    return pdf.save();
  }

  pw.Widget _pdfRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 4),
      child: pw.Row(children: [
        pw.Text(label, style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 11)),
        pw.SizedBox(width: 8),
        pw.Text(value, style: const pw.TextStyle(fontSize: 11)),
      ]),
    );
  }

  Future<void> printPdf(Uint8List pdfData) async {
    await Printing.layoutPdf(onLayout: (format) => pdfData);
  }

  Future<File> savePdfToTemp(Uint8List pdfData, String fileName) async {
    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/$fileName.pdf');
    await file.writeAsBytes(pdfData);
    return file;
  }

  // مشاركة واتساب - يفتح واتساب مع الملف
  Future<void> shareViaWhatsApp(File pdfFile, {String? phone}) async {
    // أولاً مشاركة عامة (سيظهر واتساب ضمن الخيارات)
    await Share.shareXFiles([XFile(pdfFile.path)], text: 'تقرير المحلول الوريدي - Nurse Assistant');

    // أو مشاركة مباشرة لرقم معين عبر wa.me (نص فقط - واتساب لا يدعم ملف مباشر عبر الرابط)
    if (phone != null) {
      final cleanPhone = phone.replaceAll(RegExp(r'[^0-9]'), '');
      final message = Uri.encodeComponent('تقرير المحلول الوريدي مرفق - Nurse Assistant');
      final url = Uri.parse('https://wa.me/$cleanPhone?text=$message');
      if (await canLaunchUrl(url)) {
        await launchUrl(url, mode: LaunchMode.externalApplication);
      }
    }
  }

  Future<void> sharePdfDirect(PatientInfusionRecord record) async {
    final pdfData = await generateInfusionPdf(record);
    final file = await savePdfToTemp(pdfData, 'infusion_${record.fileNumber}_${DateTime.now().millisecondsSinceEpoch}');
    await Share.shareXFiles([XFile(file.path)], text: 'تقرير المحلول - ${record.patientName}');
  }
}

